<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="2" failed="1" skipped="7">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-24T23:17:34 IST" name="Suite" finished-at="2025-04-24T23:18:07 IST" duration-ms="33257">
    <groups>
    </groups>
    <test started-at="2025-04-24T23:17:34 IST" name="Test" finished-at="2025-04-24T23:17:55 IST" duration-ms="21120">
      <class name="testcases.LoginTest">
        <test-method signature="loginTest(java.util.Hashtable)[pri:0, instance:testcases.LoginTest@2b40ff9c]" started-at="2025-04-24T23:17:34 IST" name="loginTest" data-provider="dp" finished-at="2025-04-24T23:17:42 IST" duration-ms="7897" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{browser=chrome, Password=Test22092024@198, Runmode=Y, UserName=Test22092024@198.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="quite()[pri:0, instance:testcases.LoginTest@2b40ff9c]" started-at="2025-04-24T23:17:42 IST" name="quite" finished-at="2025-04-24T23:17:42 IST" duration-ms="197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method signature="loginTest(java.util.Hashtable)[pri:0, instance:testcases.LoginTest@2b40ff9c]" started-at="2025-04-24T23:17:42 IST" name="loginTest" data-provider="dp" finished-at="2025-04-24T23:17:54 IST" duration-ms="12020" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{browser=firefox, Password=123456.0, Runmode=Y, UserName=Test@test.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed
at org.testng.Assert.fail(Assert.java:97)
at pages.SignInUpPage.doLogin(SignInUpPage.java:25)
at testcases.LoginTest.loginTest(LoginTest.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="quite()[pri:0, instance:testcases.LoginTest@2b40ff9c]" started-at="2025-04-24T23:17:54 IST" name="quite" finished-at="2025-04-24T23:17:55 IST" duration-ms="534" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- Test -->
    <test started-at="2025-04-24T23:17:55 IST" name="User Signup Test" finished-at="2025-04-24T23:18:07 IST" duration-ms="11794">
      <class name="testcases.UserSignupTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:17:34 IST" name="setUp" finished-at="2025-04-24T23:17:34 IST" duration-ms="23" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="userSignupTest(java.util.Hashtable)[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:17:55 IST" name="userSignupTest" data-provider="dp2" finished-at="2025-04-24T23:18:06 IST" duration-ms="11156" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=Y, Zipcode=2000, Name=TestK1236, browser=chrome, Address=King Street, MobileNumber=1234567890, Password=TestK@1236, LastName=1236, City=Sydney, FirstName=Testk, State=NSW, EmailAddress=TestK@1236.com, Country=Australia}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSignupTest -->
        <test-method is-config="true" signature="quite()[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:06 IST" name="quite" finished-at="2025-04-24T23:18:07 IST" duration-ms="304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method signature="userSignupTest(java.util.Hashtable)[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="userSignupTest" data-provider="dp2" finished-at="2025-04-24T23:18:07 IST" duration-ms="32" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=N, Zipcode=2900, Name=TestK1237, browser=firefox, Address=123 Main Street, MobileNumber=1478965230, Password=TestK@1237, LastName=1237, City=Melburn, FirstName=Testk, State=VIC, EmailAddress=TestK@1237.com, Country=Australia}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test : userSignupTest as the Run mode to Data set is NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test : userSignupTest as the Run mode to Data set is NO
at utilities.DataUtil.checkExecution(DataUtil.java:32)
at testcases.UserSignupTest.userSignupTest(UserSignupTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSignupTest -->
        <test-method is-config="true" signature="quite()[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="quite" finished-at="2025-04-24T23:18:07 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method signature="userSignupTest(java.util.Hashtable)[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="userSignupTest" data-provider="dp2" finished-at="2025-04-24T23:18:07 IST" duration-ms="28" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=N, Zipcode=4034, Name=TestK1238, browser=chrome, Address=Unit 16, MobileNumber=1236123612, Password=TestK@1238, LastName=1238, City=Carseldine, FirstName=Testk, State=QLD, EmailAddress=TestK@1238.com, Country=India}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test : userSignupTest as the Run mode to Data set is NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test : userSignupTest as the Run mode to Data set is NO
at utilities.DataUtil.checkExecution(DataUtil.java:32)
at testcases.UserSignupTest.userSignupTest(UserSignupTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSignupTest -->
        <test-method is-config="true" signature="quite()[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="quite" finished-at="2025-04-24T23:18:07 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method signature="userSignupTest(java.util.Hashtable)[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="userSignupTest" data-provider="dp2" finished-at="2025-04-24T23:18:07 IST" duration-ms="30" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=N, Zipcode=4000, Name=TestK1239, browser=firefox, Address=888 James Road, MobileNumber=1213121312, Password=TestK@1239, LastName=1239, City=Brisbane, FirstName=Testk, State=ACT, EmailAddress=TestK@1239.com, Country=India}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test : userSignupTest as the Run mode to Data set is NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test : userSignupTest as the Run mode to Data set is NO
at utilities.DataUtil.checkExecution(DataUtil.java:32)
at testcases.UserSignupTest.userSignupTest(UserSignupTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSignupTest -->
        <test-method is-config="true" signature="quite()[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="quite" finished-at="2025-04-24T23:18:07 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method signature="userSignupTest(java.util.Hashtable)[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="userSignupTest" data-provider="dp2" finished-at="2025-04-24T23:18:07 IST" duration-ms="27" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=N, Zipcode=2000, Name=TestK1240, browser=chrome, Address=King Street, MobileNumber=1234567890, Password=TestK@1240, LastName=1240, City=Sydney, FirstName=Testk, State=NSW, EmailAddress=TestK@1240.com, Country=Canada}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test : userSignupTest as the Run mode to Data set is NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test : userSignupTest as the Run mode to Data set is NO
at utilities.DataUtil.checkExecution(DataUtil.java:32)
at testcases.UserSignupTest.userSignupTest(UserSignupTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSignupTest -->
        <test-method is-config="true" signature="quite()[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="quite" finished-at="2025-04-24T23:18:07 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method signature="userSignupTest(java.util.Hashtable)[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="userSignupTest" data-provider="dp2" finished-at="2025-04-24T23:18:07 IST" duration-ms="28" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=N, Zipcode=2900, Name=TestK1241, browser=firefox, Address=123 Main Street, MobileNumber=1478965230, Password=TestK@1241, LastName=1241, City=Melburn, FirstName=Testk, State=VIC, EmailAddress=TestK@1241.com, Country=Canada}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test : userSignupTest as the Run mode to Data set is NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test : userSignupTest as the Run mode to Data set is NO
at utilities.DataUtil.checkExecution(DataUtil.java:32)
at testcases.UserSignupTest.userSignupTest(UserSignupTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSignupTest -->
        <test-method is-config="true" signature="quite()[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="quite" finished-at="2025-04-24T23:18:07 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method signature="userSignupTest(java.util.Hashtable)[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="userSignupTest" data-provider="dp2" finished-at="2025-04-24T23:18:07 IST" duration-ms="25" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=N, Zipcode=4034, Name=TestK1242, browser=chrome, Address=Unit 16, MobileNumber=1236123612, Password=TestK@1242, LastName=1242, City=Carseldine, FirstName=Testk, State=QLD, EmailAddress=TestK@1242.com, Country=United States}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test : userSignupTest as the Run mode to Data set is NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test : userSignupTest as the Run mode to Data set is NO
at utilities.DataUtil.checkExecution(DataUtil.java:32)
at testcases.UserSignupTest.userSignupTest(UserSignupTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSignupTest -->
        <test-method is-config="true" signature="quite()[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="quite" finished-at="2025-04-24T23:18:07 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method signature="userSignupTest(java.util.Hashtable)[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="userSignupTest" data-provider="dp2" finished-at="2025-04-24T23:18:07 IST" duration-ms="23" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=N, Zipcode=4000, Name=TestK1243, browser=firefox, Address=888 James Road, MobileNumber=1213121312, Password=TestK@1243, LastName=1243, City=Brisbane, FirstName=Testk, State=ACT, EmailAddress=TestK@1243.com, Country=United States}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test : userSignupTest as the Run mode to Data set is NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test : userSignupTest as the Run mode to Data set is NO
at utilities.DataUtil.checkExecution(DataUtil.java:32)
at testcases.UserSignupTest.userSignupTest(UserSignupTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userSignupTest -->
        <test-method is-config="true" signature="quite()[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="quite" finished-at="2025-04-24T23:18:07 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
        <test-method is-config="true" signature="quitPlaywright()[pri:0, instance:testcases.UserSignupTest@c430e6c]" started-at="2025-04-24T23:18:07 IST" name="quitPlaywright" finished-at="2025-04-24T23:18:07 IST" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitPlaywright -->
      </class> <!-- testcases.UserSignupTest -->
    </test> <!-- User Signup Test -->
  </suite> <!-- Suite -->
</testng-results>
